create table department
(
  id   bigint generated by default as identity,
  name varchar(255) not null,
  primary key (id)
);

create table employee
(
  id            bigint generated by default as identity,
  age           integer      not null,
  department_id bigint       not null,
  first_name    varchar(255) not null,
  last_name     varchar(255),
  mail          varchar(255),
  primary key (id)
);